/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Breadcrumb: typeof import('./src/components/Breadcrumb/index.vue')['default']
    Content: typeof import('./src/components/Message/content/index.vue')['default']
    Form: typeof import('./src/components/Base/Form/src/Form.vue')['default']
    MarkdownEditor: typeof import('./src/components/MarkdownEditor/src/MarkdownEditor.vue')['default']
    Message: typeof import('./src/components/Message/index.vue')['default']
    Modal: typeof import('./src/components/Base/Modal/src/Modal.vue')['default']
    NBreadcrumb: typeof import('naive-ui')['NBreadcrumb']
    NBreadcrumbItem: typeof import('naive-ui')['NBreadcrumbItem']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NInputGroup: typeof import('naive-ui')['NInputGroup']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NMenu: typeof import('naive-ui')['NMenu']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NModal: typeof import('naive-ui')['NModal']
    NRadio: typeof import('naive-ui')['NRadio']
    NRadioGroup: typeof import('naive-ui')['NRadioGroup']
    NSpace: typeof import('naive-ui')['NSpace']
    NTabPane: typeof import('naive-ui')['NTabPane']
    NTabs: typeof import('naive-ui')['NTabs']
    NWatermark: typeof import('naive-ui')['NWatermark']
    PoweredBy: typeof import('./src/components/PoweredBy/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./src/components/Base/Search/src/Search.vue')['default']
    SwitchEnv: typeof import('./src/components/SwitchEnv/index.vue')['default']
    Table: typeof import('./src/components/Base/Table/src/Table.vue')['default']
    Upload: typeof import('./src/components/Base/Upload/src/Upload.vue')['default']
  }
}
